### ISSUE TITLE
解析度

### ISSUE THREAD

**Issue by lucemia** [livingbio/imaginaire-fsvid2vid#1]
![截圖 2021-11-02 上午10 06 18](https://user-images.githubusercontent.com/432851/139775016-f2721ce9-a58b-48d7-b8f2-93989014d3af.png)

- 這裡的解析度指的是要 輸入的解析度 而不是輸出的解析度是嗎? (上面有說模型的 "最大輸出解析度：512x512")
- Sample 看起來都沒有到 512x512 的畫質，是原本就這樣嗎? 如果套上提高解析度的模型會比較好嗎? like this: https://www.pkstep.com/archives/68642

**Comment by achen353** [comment]
> * 這裡的解析度指的是要 輸入的解析度 而不是輸出的解析度是嗎? (上面有說模型的 "最大輸出解析度：512x512")

input 的影像資料有 1 張 reference image 和多張 driving image (video)，前者是要使用的人臉、後者是要使用的表情變化（影片），資料進入模型後都會 crop 和 resize。而表格裡顯示的是 driving image 的解析度（driving image 有很多張，理論上在 人臉定位和 crop/resize 上會對 runtime 影像較大，所以紀錄的是 driving image 的解析度），我再把 README 修正一下。

Disclaimer: output image quality 是看 reference image。

> * Sample 看起來都沒有到 512x512 的畫質，是原本就這樣嗎? 如果套上提高解析度的模型會比較好嗎? like this: https://www.pkstep.com/archives/68642

應該是因為 sample 的 reference image 原本解析度不高，加上臉部面積小裁切再放大之後就看起來模糊，我找幾個 HD 的 reference image 試試看

**Comment by achen353** [comment]
即使用較高解析度的 reference image，輸出的影片還是會模糊，臉上的細節會消失，應該是模型本身的問題，線上的修影片程式也沒辦法調

以下用不同的 reference image 測試，driving video 分別用解析度較低（白人女性）和較高（黑人男性）做測試：

https://user-images.githubusercontent.com/21190239/139868413-1f8877d7-36fc-4a1e-be3b-dbf1d5a0124f.mp4

這個和上面的 reference image input 一樣，似乎是在進入模型 crop/resize 是出問題，重試幾遍都有問題

https://user-images.githubusercontent.com/21190239/139868462-ba571e21-f348-4017-a0b3-66575ce7382a.mp4

這幾個臉部毛孔和粗糙程度消失的特別明顯

https://user-images.githubusercontent.com/21190239/139868480-feaa4dad-02f1-46ea-b0ec-65c19aeb6230.mp4

https://user-images.githubusercontent.com/21190239/139868492-def337ac-5ba4-48b8-a2d8-4b490ba6fea3.mp4

https://user-images.githubusercontent.com/21190239/139868605-1634e923-8c50-4ad3-982e-eac3bc733142.mp4

https://user-images.githubusercontent.com/21190239/139868610-0fdd9c2b-faee-43bc-affe-5c2003d7aa4a.mp4

下面兩個用華人女性的結果，因為 reference image 臉部的細節本來就比較少，臉部色彩也比較均勻（陰影變化不大），所以模糊化最不明顯

https://user-images.githubusercontent.com/21190239/139868646-36d8ff01-f3da-43ed-bf2a-2906a70096d1.mp4

https://user-images.githubusercontent.com/21190239/139868667-2889e5fa-6d15-4998-b2b7-3af57c43e5bd.mp4

**Comment by lucemia** [comment]
把這些心得寫到 Blog 裡吧
