### ISSUE TITLE
CPU

### ISSUE THREAD

**Issue by vickyliin** [livingbio/imaginaire-fsvid2vid#3]
需確認在 host 沒有 gpu/cuda 的狀況下，docker container 也能跑起來 & 正常 inference（不論效能）

**Comment by achen353** [comment]
host 沒有 gpu/cuda 的情況下無法使用，有些模型使用到的 third party 架構沒有提供 CPU 版本的

Related Issue/PR: 
- [Resample2D function to CPU compatible code](https://github.com/NVIDIA/flownet2-pytorch/issues/190)
- [Implementations of the custom layers in C++ and Native Pytorch for CPU support.](https://github.com/NVIDIA/flownet2-pytorch/pull/212)

另外做了幾個測試：
|            Host            |            Base Image            |                Pytorch               |               結果               |
|------------------ |--------------------------|--------------------------|----------------------|
| macOS Monterey | nvidia/cuda:11.1.1-cudnn8-devel-ubuntu20.04 | 1.9+cu111 | build image 時 pip install -r requirements 會有問題，run container 之後需要把沒執行到指令執行一遍，編譯 third party 模型會找不到 CUDA 報錯
| macOS Monterey | ubuntu:20.24 | 1.10+cpu | build image 時 pip install -r requirements 會有問題，run container 之後需要把沒執行到指令執行一遍，編譯 third party 模型會找不到 CUDA 報錯
| Ubuntu 20.04 Focal | nvidia/cuda:11.1.1-cudnn8-devel-ubuntu20.04 | 1.9+cu11 | build image 時編譯 third party 模型會找不到 CUDA 報錯
| Ubuntu 20.04 Focal | ubuntu:20.24 | 1.10+cpu | build image 時編譯 third party 模型會找不到 CUDA 報錯
